### ISSUE TITLE
ACME DNS 配置错误

### ISSUE THREAD

**Issue by kanao7** [seagullz4/hysteria2#30]
官方示例
```
acme:
  domains:
    - "*.example.com"
  email: your@email.address
  type: dns
  dns:
    name: cloudflare
    config:
      cloudflare_api_token: Dxabckw9dB_jYBdi89kgyaS8wRjqqSsd679urScKOBP
```
使用脚本生成的配置
```
acme:
 domains:
 - *.example.com
 email: your@email.address
type: dns
dns:
  name: cloudflare
  config:
    cloudflare_api_token: Dxabckw9dB_jYBdi89kgyaS8wRjqqSsd679urScKOBP
```
缩进不正确导致hy2运行失败，修改成正确格式后hy2正常运行。望改进。
另外能否增加启动/暂停/重启内核功能，更方便操作
